name: "Pharo setup"
description: "Install Pharo Virtual Machine and image."

inputs:
  version:
    description: "Pharo version number to install. (e.g. 13)"
    required: true
  imageName:
    description: "Save the Pharo image under this name"
    default: "Pharo"
  imageDir:
    description: "Path where the Pharo image will be downloaded"
    default: ${{ github.workspace}}

runs:
  using: "composite"
  steps:
    - name: Set system properties
      run: |
        echo "HOST_ARCH=x86_64" >> $GITHUB_ENV
        case "${RUNNER_OS}" in
          macOS)    HOST_OS=Darwin;;
          *)        HOST_OS=$RUNNER_OS
        esac
        echo "HOST_OS=$HOST_OS" >> $GITHUB_ENV
        echo "FILES_URL=https://files.pharo.org/get-files/${{ inputs.version }}0" >> $GITHUB_ENV
      shell: bash

    - name: Install Pharo VM
      run: |
        VM_STATUS="stable"
        URL="${{ env.FILES_URL }}/pharo-vm-${{ env.HOST_OS }}-${{ env.HOST_ARCH }}-${VM_STATUS}.zip"
        echo "Downloading $URL"
        curl -L $URL -o pharo-vm.zip
        unzip pharo-vm.zip -d pharo-vm
        rm -f pharo-vm.zip
      shell: bash

    - name: Get Pharo image
      run: |
        IMAGE_PATH=pharoImage-x86_64.zip
        URL="${FILES_URL}/pharoImage-${HOST_ARCH}.zip"
        echo "Downloading $URL"
        curl -L ${URL} -o pharo-image.zip
        unzip pharo-image.zip -d image
        rm -f pharo-image.zip
        find image -name '*.image' -exec mv '{}' ${{ inputs.imageDir }}/${{ inputs.imageName }}.image \;
        find image -name '*.changes' -exec mv '{}' ${{ inputs.imageDir }}/${{ inputs.imageName }}.changes \;
        mv image/*.sources ${{ inputs.imageDir }}
        rm -rf image
        ls
      shell: bash

    - name: Append Pharo to the PATH
      run: |
        echo "$(pwd)/pharo-vm" >> $GITHUB_PATH
        VM_PATH=$(pwd)
        case "${RUNNER_OS}" in
          Linux)    PHARO=$VM_PATH/pharo;;
          Windows)  PHARO=$VM_PATH\PharoConsole.exe;;
          macOS)    PHARO=$VM_PATH/Pharo.app/Contents/MacOS/Pharo;;
        esac
        echo "Setting \$PHARO alias to $PHARO"
        echo "PHARO=$PHARO" >> $GITHUB_ENV

      shell: bash
